apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: vmexamples
spec:
  selector:
    vm.kubevirt.io/name: database # <- VM name
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

#-----------------------------

apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: vmexamples
spec:
  selector:
    env: webapp # <- Custom label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
