kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: hpa-vmpool-fedora
  namespace: igor
spec:
  scaleTargetRef:
    kind: VirtualMachinePool
    name: vmpool-linux
    apiVersion: pool.kubevirt.io/v1alpha1
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40
